### ISSUE TITLE
Configure modded tools?

### ISSUE THREAD

**Issue by huntersan9** [kyrptonaught/DiggusMaximus#10]
Using Minecraft 1.15.2 with fabric.  Using ModMenu as well.

Is it possible to add new tools?  

Veinminer used a command /vm pickaxe add modded_pickaxe and ore excavator used a menu and config file list.  This is a feature that I would love to have.  Thanks!

**Comment by kyrptonaught** [comment]
What tool are you trying to use? Diggus considers any item that’s damageable a tool

**Comment by huntersan9** [comment]
Tech Reborn Basic Drill 

techreborn:basic_drill

**Comment by kyrptonaught** [comment]
This has been added
