### ISSUE TITLE
mc hangs when digging a tree

### ISSUE THREAD

**Issue by maxvar** [kyrptonaught/DiggusMaximus#11]
Hi! I'm testing a new game setup, so this is probably a conflict or another mod's fault.
The jvm just hangs (not just mc crashes, so there is not a crashlog) when I cut a tree block very much like shown on your demo in mod's description on curseforge.
How can I investigate the issue other than removing other mods one by one?
Here is a game session log before it failed: https://pastebin.com/Du7fKpU1

**Comment by maxvar** [comment]
looks like that https://raw.githubusercontent.com/maxvar/scrap/master/hangs.jpg

**Comment by kyrptonaught** [comment]
Have you verified it works alone with no other mods? Does it work on other blocks like dirt/stone? Or it it only trees that cause the issue? Then I’d say start by removing the optimization mods like lithium and phosphor, and any other mods having to do with trees like leaf decay.

**Comment by maxvar** [comment]
Yes, your are right, I checked those two mods and that was phosphor which causes the hang.
(proximity of a grass block should have been a coincidence, as I quickly reproduced the hang in a freshly created flatworld with a couple of oak logs and a wooden axe).
I'll check the updated version of it (Angeline released an update just an hour ago) and if it fails, I'll report it to her.
Thanks again and good luck!
