### ISSUE TITLE
Spruce leaves don't decay after mining logs

### ISSUE THREAD

**Issue by JJSax** [kyrptonaught/DiggusMaximus#15]
The other tree types are fine from my testing, but when vein mining spruce logs, the leaves don't decay.  This happens with both regular sized spruce trees and the 2x2 trees.  On occasion the top few layers decayed on the large trees, but the rest remained.

diggus maximus version : 1.2.10

**Comment by kyrptonaught** [comment]
Have you verified this happens with only diggus installed?

**Comment by JJSax** [comment]
> Have you verified this happens with only diggus installed?

I have now.  Probably should have done that before because now it's working fine.  Even tried with leaf decay mod on and it still worked fine.  Went back to the same game I was having the issue in and it is fine there too.  Not sure what happened.  I'll go ahead and close this and back away slowly.
