### ISSUE TITLE
Exhaustion not working on 1.2.10 release

### ISSUE THREAD

**Issue by 91bba748** [kyrptonaught/DiggusMaximus#16]
1.15.2 client. Log shows nothing. Full food bar after mined 8 stack of stones.

**Comment by kyrptonaught** [comment]
Are you playing on a server? Can you post the contents of the config(config.json5)?

**Comment by 91bba748** [comment]
I'm on local single player world.
Fabric API build 312

    {
        // Mod enabled or disabled
        "enabled": true,
        // Activation key
        "keybinding": "key.keyboard.grave.accent",
        // Should mine diagonally
        "mineDiag": true,
        // Maximum number of blocks to mine
        "maxMinedBlocks": 64,
        // Maximum distance from start to mine
        "maxMineDistance": 10,
        // Automatically pick up drops
        "autoPickup": true,
        // Tool required to excavate
        "requiresTool": true,
        // Stop before tool breaks
        "dontBreakTool": true,
        // Stop excavating when tool breaks
        "stopOnToolBreak": true,
        // Should tool take durability
        "toolDurability": true,
        // Should player get exhaustion
        "playerExhaustion": true,
        // Multiply exhaustion when excavating
        "exhaustionMultiplier": 1.0,
        // Other items to be considered tools: "minecraft:stick"
        "tools": []
    }

**Comment by kyrptonaught** [comment]
Can you try this build? I changed the way I modified exhaustion so it might fix the problem for you.

Also mining does give a very small amount of exhaustion(0.005F) per block mined, perhaps try playing with the exhaustion modifier to verify it is in fact working?
[diggusmaximus-1.2.11.zip](https://github.com/kyrptonaught/DiggusMaximus/files/4708346/diggusmaximus-1.2.11.zip)
