### ISSUE TITLE
Conflicts with Tree datapacks

### ISSUE THREAD

**Issue by xjiro** [kyrptonaught/DiggusMaximus#19]
Diggus Maximus seems to conflict with and silently break datapacks that fell trees.

I tested with [TreeCapitator](https://www.planetminecraft.com/data-pack/treecapitator-datapack-1-13/) and [Timber](https://www.planetminecraft.com/data-pack/timber-datapack/), isolating for Diggus Maximus.

**Comment by kyrptonaught** [comment]
I'm not sure how to fix this other than suggestion to blacklist logs in the config?
