### ISSUE TITLE
diggus ignores any permissions

### ISSUE THREAD

**Issue by Monster-Zer0** [kyrptonaught/DiggusMaximus#23]
vanilla spawn protect. get off my lawn and flan are not safe from diggus.

you can bypass any claim or protection system with diggus.

**Comment by kyrptonaught** [comment]
Hm Diggus is just triggering the vanilla method of breaking a block. Odd that it isn't stopped, I'll investigate how they stop it

**Comment by Flemmli97** [comment]
using fabric api only version 0.19+ have an additional block break callback at the place where the player actually breaks the block. previously it was only at the place where a player is trying to break (mine) a block
