### ISSUE TITLE
A strange error occurred when I starting minecraft

### ISSUE THREAD

**Issue by originalFactor** [kyrptonaught/DiggusMaximus#30]
I added diggusmaximus-1.4.5-1.17.jar to my minecraft, but when I started, fabric showed an error.
![image](https://user-images.githubusercontent.com/72148355/127341062-9ee16c49-9195-435f-9ed9-b3714c72ff85.png)

**Comment by kyrptonaught** [comment]
You must also install the mod "fabric api" you can find it on curseforge

**Comment by originalFactor** [comment]
Okay. I see it. Thanks.
