### ISSUE TITLE
{LOW PRIORITY BUG} Can't Excavate with Empty Hand

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [kyrptonaught/DiggusMaximus#32]
You can't excavate when your hand is empty. At first, I thought this was a feature, and you needed to have the correct tool to excavate, but I noticed that you can excavate logs with dirt, and noticed it was a bug.

**Comment by kyrptonaught** [comment]
I cannot recreate this, I can mine with my hand just fine. Have you changed the config option "requires tool"?

**Comment by BeansBeefBroccoli** [comment]
No, but I am playing AoF 4, so maybe they did.

**Comment by BeansBeefBroccoli** [comment]
[AoF 4 Diggus Maximus CFG Folder](https://github.com/TeamAOF/All-of-Fabric-4/tree/main/config/diggusmaximus)
