### ISSUE TITLE
1.17.1 Forge says mod is not compatable. Cannot activate either...

### ISSUE THREAD

**Issue by RepoDraghon** [kyrptonaught/DiggusMaximus#36]
Picture [https://repodraghon.tumblr.com/post/666416162469511168](url)

Modpack is latest "Better Minecraft [FORGE]"

Also, tried removing the Tree mods and it still didn't work.

**Comment by kyrptonaught** [comment]
DiggusMaximus is a mod for Fabric, it is not compatible with Forge. Did you add this mod to the modpack or was it already there? 

Sorry for the confusion!

**Comment by RepoDraghon** [comment]
That would explain a lot... It's mentioned it was based off of mods made for Forge but either I'm blind or nowhere in the description says it is for Fabric. That's where the confusion is.

**Comment by kyrptonaught** [comment]
The short project summary mentions that it is a mod for Fabric, and all the jar downloads are marked as compatible with Fabric. I blame curseforge for not giving us a better way of marking a mod for Fabric.

That said I did mention it in the description now
