### ISSUE TITLE
Gradlew cant get config file

### ISSUE THREAD

**Issue by MristeX** [kyrptonaught/DiggusMaximus#38]
I cloned your reposite to my IDLE and when i run the build.gradle an error occures telling me 

Could not GET 'https://dl.bintray.com/kyrptonaught/kyrptconfig/net/kyrptonaught/kyrptconfig/1.1.8-1.16/kyrptconfig-1.1.8-1.16.pom'. Received status code 403 from server: Forbidden

**Comment by kyrptonaught** [comment]
In the build.gradle you'll have to change my repository to "https://maven.kyrptonaught.dev"

**Comment by kyrptonaught** [comment]
See line 17 [here](https://github.com/kyrptonaught/DiggusMaximus/blob/1.17/build.gradle)

**Comment by MristeX** [comment]
Thanks for the quick response.
Now a new error occurs:
Caused by: java.io.IOException: Downloaded file from http://resources.download.minecraft.net/bd/bdf48ef6b5d0d23bbb02e17d04865216179f510a to C:\Users\user\.gradle\caches\fabric-loom\assets\objects\bd\bdf48ef6b5d0d23bbb02e17d04865216179f510a and got unexpected hash of bdf48ef6b5d0d23bbb02e17d04865216179f510a expected bdf48ef6b5d0d23bbb02e17d04865216179f510a

But the hashes are identical.
Do you now why?

**Comment by kyrptonaught** [comment]
Can you clear all the gradle cache and try to start it again? Sometimes gradle can be funky and a clear and reset can fix issues

**Comment by MristeX** [comment]
That helped but:
C:\Users\user\Downloads\DiggusMaximus-master\src\main\java\net\kyrptonaught\diggusmaximus\config\Blacklist.java:4:43
java: package net.kyrptonaught.kyrptconfig.config does not exist

**Comment by MristeX** [comment]
Sorry for spamming you. Its the first time i try to gradlew a mod

**Comment by MristeX** [comment]
Now it runs. But I cant find a .jar file. Where will it be generate?

**Comment by MristeX** [comment]
Thank you for your time. Unfortunatly i dont find a way to donwgrade my java so gradle except it.
