### ISSUE TITLE
mod isn't loaded

### ISSUE THREAD

**Issue by Zemogiter** [kyrptonaught/DiggusMaximus#39]
Mod file is in mods directory but does not load at all (not visible in mods menu, ~ does nothing). Forge 39.0.8
[debug.log](https://github.com/kyrptonaught/DiggusMaximus/files/7780205/debug.log)
[latest.log](https://github.com/kyrptonaught/DiggusMaximus/files/7780206/latest.log)

**Comment by kyrptonaught** [comment]
Unfortunately this mod does not work with forge, only fabric.
