### ISSUE TITLE
Stone affected by gravity after vein mining stone 

### ISSUE THREAD

**Issue by TheRanker** [kyrptonaught/DiggusMaximus#40]
This may be a mod interaction conflict. But mining normally does not cause stone to fall like it's affected by gravity. Using the mod to vein mine however. Causes stone to fall like gravel. 

It does not happen with the mod removed. 

It is in a modpack with 275 mods. One of them is physics mod.  Which enables these features. But that feature is off and does not happen at all. 

Maybe the vein mining mod is interacting with that physics mod somehow? 

Nothing in log states anything. 

Using the latest version for 1.18.1 fabric. 
Fabric 0.12.12 

I can provide more info and testing as needed. Just need direction. :) 

Thanks for looking!

**Comment by kyrptonaught** [comment]
I'm fairly certain it is an interaction with the physics mod, what mod is it?

You can confirm if it is an interaction with the physics mod by removing it and seeing if the issue persists.

**Comment by TheRanker** [comment]
Interaction as stated does not happen with diggus mod removed.  And only happens when you vein mine. 
The mod is. https://www.curseforge.com/minecraft/mc-mods/physics-mod

**Comment by kyrptonaught** [comment]
Ah I meant remove the physics mod, I should've worded that a bit clearer

**Comment by TheRanker** [comment]
I'll check that side of things tomorrow. Won't be able to check that tonight will require a bit of time back at pc.

**Comment by TheRanker** [comment]
after testing with physics removed.. the stone blocks still fall like gravel. 

will have to test more with half mods of modapck and start to find the culprit of it.  going to start with fabric 0.12.12 and diggus mod.  make sure i dont see it happen there before i start . this may take some time.

**Comment by TheRanker** [comment]
We can close this.  Issue was not related to this Mod at all. But another mod I found while resolving the issue. Sorry for the inconvenience.
