### ISSUE TITLE
Mod Menu custom groups config is limited to 32 Characters disabling ability to group blocks

### ISSUE THREAD

**Issue by Drunkender** [kyrptonaught/DiggusMaximus#44]
When trying to create a custom group in the mod menu(minecraft:iron_ore, minecraft:deepslate_iron_ore) it gets cut off at (minecraft:iron_ore, minecraft:de). When I manually add it to the grouping.json5 file they will still not excavate together.

Minecraft 1.18.1, fabric 0.12.12, DiggusMaximus 1.5.2-1.18

https://i.imgur.com/gAHMaJC.png
![config_file](https://user-images.githubusercontent.com/14418412/151680955-f0a9a10c-9f2b-4c8c-9a00-96fdada5b0a5.png)

https://i.imgur.com/hbNV8FX.png
![mod_menu](https://user-images.githubusercontent.com/14418412/151680960-777d0cf2-669c-48eb-938e-a875be3951b4.png)

**Comment by Drunkender** [comment]
I've also tried enabling Tag Grouping like your example [here](https://i.imgur.com/mgZ9j41.png) to no avail.

**Comment by kyrptonaught** [comment]
I redid the grouping config option in mod menu to make it a bit easier to use. This does increase the limit too. I'll get this released soon

![image](https://user-images.githubusercontent.com/3196164/151908759-ad0be6dc-d67b-4690-80b0-12741614d3d3.png)

**Comment by Drunkender** [comment]
Nice! Thank you very much. Block grouping was one of my favorite features of the Ore Excavation mod for Forge. Would love to see it working in DiggusMaximus aswell!

Cheers

**Comment by kyrptonaught** [comment]
Here is a pre-release

[diggusmaximus-1.5.3-1.18.zip](https://github.com/kyrptonaught/DiggusMaximus/files/7975704/diggusmaximus-1.5.3-1.18.zip)

**Comment by Drunkender** [comment]
Works perfectly! Although I found a way to crash it already =D.
Pasting the results from /ct hand( <item:denseores:dense_iron_ore>  * 64) into the block group gave me this. (Was doing this to add new blocks quickly from the dense ores mod)

> ---- Minecraft Crash Report ----
> // Daisy, daisy...
> 
> Time: 1/31/22, 9:40 PM
> Description: Rendering screen
> 
> net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: <item:denseores:dense_iron_ore> * 64

If you want the whole stack trace let me know. Other than that hiccup I love it!

**Comment by kyrptonaught** [comment]
You need to remove the * 64. The block listed should only be it's ID. But It shouldn't crash, that should be fixed

**Comment by Drunkender** [comment]
I was planning on editing it in the config screen, it was just a fast way to get the item id. Had all of the iron ores and dense iron ores in one block group.

Thank you very much for this!
