### ISSUE TITLE
Shulker boxes lose NBT

### ISSUE THREAD

**Issue by cplir-c** [kyrptonaught/DiggusMaximus#5]
I vein-mined a group of 4 purple shulker boxes with a rock cutter from techreborn, and only the one that I started mining the 'vein' on kept its contents.
I'm playing on 1.15-pre6
I hope this helps!

**Comment by kyrptonaught** [comment]
https://github.com/kyrptonaught/DiggusMaximus/commit/5d0616c164ab68386e8fa8487c662d65698791da
Fixed, build uploading on curse
