### ISSUE TITLE
Mod conflicts with Multisleep- cannot start server

### ISSUE THREAD

**Issue by Dwooll94** [kyrptonaught/DiggusMaximus#54]
As long as diggusmaximus and multisleep aren't enabled at the same time the server loads normally, but when they're both enabled the server crashes with an exception provided by diggusmaximus 
`Caused by: java.lang.NoSuchMethodError: 'void blue.endless.jankson.Jankson$Builder.<init>(java.lang.Boolean)'
        at net.kyrptonaught.kyrptconfig.config.CustomJankson.customJanksonBuilder(CustomJankson.java:9) ~[kyrptconfig-1.4.11-1.19-d2b902df35f85091.jar:?]`
<details>
<summary>Full Log file</summary>
> PS D:\Documents\mc118\minecraft> java -Xmx4G -jar fabric-server-mc.1.19-loader.0.14.8-launcher.0.11.0.jar nogui
> Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
> [00:07:49] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
> [00:07:49] [main/INFO]: Loading 46 mods:
>         - blue_endless_jankson 1.2.1 via jankson
>         - diggusmaximus 1.5.7-1.19
>         - fabric 0.57.0+1.19
>         - fabric-api-base 0.4.9+e62f51a3a9 via fabric
>         - fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
>         - fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
>         - fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
>         - fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
>         - fabric-commands-v0 0.2.23+df3654b3a9 via fabric
>         - fabric-containers-v0 0.1.27+df3654b3a9 via fabric
>         - fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
>         - fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
>         - fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
>         - fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
>         - fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
>         - fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
>         - fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
>         - fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
>         - fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
>         - fabric-item-api-v1 1.5.4+767db26ea9 via fabric
>         - fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
>         - fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
>         - fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
>         - fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
>         - fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
>         - fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
>         - fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
>         - fabric-networking-v0 0.3.14+df3654b3a9 via fabric
>         - fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
>         - fabric-particles-v1 1.0.8+dc39553aa9 via fabric
>         - fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
>         - fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
>         - fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
>         - fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
>         - fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
>         - fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
>         - fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
>         - fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
>         - fabricloader 0.14.8
>         - jankson 4.1.1+j1.2.1 via libgui
>         - java 17
>         - kyrptconfig 1.4.11-1.19 via diggusmaximus
>         - libgui 6.0.0+1.19 via multisleep
>         - libninepatch 1.1.0 via libgui
>         - minecraft 1.19
>         - multisleep 1.4
> [00:07:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Documents/mc118/minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
> [00:07:49] [main/INFO]: Compatibility level set to JAVA_17
> [00:07:53] [main/INFO]: Building unoptimized datafixer
> [00:07:54] [main/INFO]: [Multiplayer Sleep] Initializing
> [00:07:54] [main/ERROR]: Failed to start the minecraft server
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'diggusmaximus'!
>         at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
>         at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
>         at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19-loader.0.14.8-launcher.0.11.0.jar:0.11.0]
> Caused by: java.lang.NoSuchMethodError: 'void blue.endless.jankson.Jankson$Builder.<init>(java.lang.Boolean)'
>         at net.kyrptonaught.kyrptconfig.config.CustomJankson.customJanksonBuilder(CustomJankson.java:9) ~[kyrptconfig-1.4.11-1.19-d2b902df35f85091.jar:?]
>         at net.kyrptonaught.kyrptconfig.config.ConfigManager.<init>(ConfigManager.java:21) ~[kyrptconfig-1.4.11-1.19-d2b902df35f85091.jar:?]
>         at net.kyrptonaught.kyrptconfig.config.ConfigManager$MultiConfigManager.<init>(ConfigManager.java:80) ~[kyrptconfig-1.4.11-1.19-d2b902df35f85091.jar:?]
>         at net.kyrptonaught.diggusmaximus.DiggusMaximusMod.<clinit>(DiggusMaximusMod.java:17) ~[diggusmaximus-1.5.7-1.19.jar:?]
>         at java.lang.Class.forName0(Native Method) ~[?:?]
>         at java.lang.Class.forName(Class.java:467) ~[?:?]
>         at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
>         ... 8 more
</details>

As in the log, this is with diggusmaximus-1.5.7-1.19 and multisleep-1.4 (for MC 1.19).

**Comment by kyrptonaught** [comment]
Ah shoot this is from my config lib

**Comment by kyrptonaught** [comment]
This was fixed in 1.5.8

**Comment by litoj** [comment]
Why is this issue still open?
