### ISSUE TITLE
Update to 1.19.2

### ISSUE THREAD

**Issue by ChacePratt** [kyrptonaught/DiggusMaximus#62]
No issues, just suggesting an update to 1.19.2 to keep up with bug fixes.

Best regards,
Gitko

**Comment by kyrptonaught** [comment]
Does it work on 1.19.2?

**Comment by ChacePratt** [comment]
Sure does... I'm so sorry. I was under the impression that a 1.19 mod would automatically throw an error that prevents the mod to load on 1.19.2.

Sorry for wasting your time!
