### ISSUE TITLE
duplicate option in settings

### ISSUE THREAD

**Issue by litoj** [kyrptonaught/DiggusMaximus#65]
![image](https://user-images.githubusercontent.com/54900518/209536541-00b2e1ee-84e7-49c9-a9c1-68655bab6b68.png)

**Comment by JosefLitos** [comment]
Plus whenever changing settings, the excavate shape resets to layer.

**Comment by litoj** [comment]
Plus counting mined blocks with shape excavate doesn't work properly (setting max 90 blocks mines only a 5 blocks long 3x3 tunnel, instead of 10) and 180 blocks mine not evet full 7 blocks long tunnel.
How is it so random?

**Comment by kyrptonaught** [comment]
Thanks for finding the duplicated option, not sure how that ended up there.

I'm gonna look into the other issues mentioned

**Comment by litoj** [comment]
I opened the block counting as a separate issue - #67 . I am currently trying different changes in the code, but so far no luck.
