### ISSUE TITLE
Crash with Allure 

### ISSUE THREAD

**Issue by CrankySupertoon** [kyrptonaught/DiggusMaximus#9]
https://pastebin.com/p3BQdPcP

**Comment by CrankySupertoon** [comment]
Cross Posted to Allure's Issue tracker they dont have (curseforge comments)

https://www.curseforge.com/minecraft/mc-mods/allure?comment=86

**Comment by kyrptonaught** [comment]
See: https://github.com/kyrptonaught/DiggusMaximus/issues/8

Allure is not using mixins in a way that makes it compatible with other mods. The issue is on their end. I have tried reaching out to them but no response heard back

**Comment by kyrptonaught** [comment]
This should be resolved with 1.2.8
